greenplum-db/greenplum-database-release

Makefile, concourse/pipelines/gpdb_opensource_release.yml, concourse/scripts/build_gpdb_debian.bash, concourse/scripts/compile_gpdb_oss.bash, concourse/scripts/gpdb_github_release.bash, concourse/tasks/build_gpdb_debian.yml, concourse/tasks/compile_gpdb_oss.yml, concourse/tasks/gpdb_github_release.yml
It consist following pr and commit from previous work with @bradfordboyle 
https://github.com/greenplum-db/gpdb/pull/7906 all ready merged
https://github.com/greenplum-db/gpdb/pull/7976 not merged
https://github.com/BaiShaoqi/gpdb/commit/ccc43d03728f175d2fb71129c7210e1d4679e590 not merged
It's related to tracker 
https://www.pivotaltracker.com/story/show/166344814
https://www.pivotaltracker.com/story/show/166369681
https://www.pivotaltracker.com/story/show/166344846
dev pipeline: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-new_repo-sbai
TODO, https://github.com/pivotal/gp-continuous-integration#gpdb-oss-release is not needed, because in this repo, can use make set-dev to do the same thing.
TODO,  the yml file …
=> Move task from gpdb to this repo

Makefile, concourse/scripts/compile_gpdb_oss.bash, concourse/tasks/compile_gpdb_oss.yml
Now the ORCA_TAG can be automatically extracted from gpdb src.
make set-dev do not comment out the tag_filter
Use right pipeline name to fly -t prod unpause-pipeline
Dev pipeline: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-fix-make-sbai
=> Fix set-pipeline

concourse/pipelines/gpdb_opensource_release.yml, concourse/scripts/build_gpdb_deb.bash, concourse/tasks/build_gpdb_deb.yml, concourse/tasks/compile_gpdb_oss.yml, concourse/tasks/gpdb_github_release.yml
To make build_gpdb_debian.yml build_gpdb_debian.bash also works for
closed repos, the license_file input should be
made optional, because it now only need in open source debian build.
Also make gpdb_src optional, because other repos do not use
gpdb_src to extract the actual version, but use a fake GPDB_VERSION:
"1.0.0"
Dev pipeline: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-rm-dup-deb-sbai
=> Update closed repos to use `greenplum-database-release` for deb packaging

concourse/scripts/compile_gpdb_oss.bash
gporca builds multiple shared-objects that need to be included in the
greenplum-database binary distribution. This commit adds the missing
libraries.
=> Include missing gporca libraries

concourse/scripts/build_gpdb_rpm.bash, concourse/scripts/greenplum-db.spec, concourse/tasks/build_gpdb_rpm.yml
dev: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-doc-sbai
now, after `rpm -i greenplum-db-6.0.0-beta.4-rhel6-x86_64.rpm` the doc will be showing in `/usr/share/doc/greenplum-database-6.0.0_beta.4/copyright` and also `/usr/local/greenplum-database/copyright`
=> OSL attribution file of Open Source Greenplum 6 Database Server in the RPM Installers

concourse/scripts/build_gpdb_rpm.bash, concourse/scripts/greenplum-db.spec
the file content's is not look like COPYRIGHT, so use
open_source_license_greenplum_database.txt as the suggested name
Co-authored-by: Amil Khanzada <akhanzada@pivotal.io>
Co-authored-by: Kris Macoskey <kmacoskey@pivotal.io>
Co-authored-by: Shaoqi Bai <sbai@pivotal.io>
=> Use open_source_license_greenplum_database.txt as the name

concourse/oss/rpmbuild.py, concourse/pipelines/gpdb_opensource_release.yml, concourse/scripts/greenplum-db.spec, concourse/tasks/build_gpdb_rpm.py, concourse/tasks/publish_to_ppa.py, concourse/tests/build_gpdb_rpm_test.py
Historically, Greenplum has been installed into a directory named
"greenplum-db" and we would like to maintain this convention. In order
to reduce confusion, we are changing the package name to match with the
installation prefix.
Co-authored-by: Bradford D. Boyle <bboyle@pivotal.io>
Co-authored-by: Shaoqi Bai <sbai@pivotal.io>
=> Change the package name to greenplum-db

concourse/oss/ppa.py, concourse/oss/rpmbuild.py, concourse/oss/utils.py, concourse/pipelines/gpdb_opensource_release.yml, concourse/scripts/build_gpdb_deb.bash, concourse/tasks/build_gpdb_deb.yml, concourse/tasks/build_gpdb_rpm.py, concourse/tasks/build_gpdb_rpm.yml, concourse/tasks/publish_to_ppa.py, concourse/tasks/publish_to_ppa.yml, concourse/tests/build_gpdb_rpm_test.py, concourse/tests/ppa_test.py
* Include the open-source OSLO license and EUAL files for Enterprise gpdb.
* Include the LICENSE, COPYRIGHT, NOTICE and OSLO license files for OSS gpdb
Dev pipelines:
https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-add_lic_copyright_files-baotingfang
https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/dev-6X-RELEASE-add_osl_lic-baotingfang
https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/dev-gpdb6-integration-testing-add_osl_lic-baotingfang
=> Add the LICENSE and COPYRIGHT file to installer for OSS gpdb

ci/concourse/scripts/gpdb_github_release.bash
Exclude the .git .travis.yml files, support tar.gz and zip format.
The second solution for archiving gpdb source code.
[#168285479]
Co-authored-by: Xin Zhang <xzhang@pivotal.io>
Co-authored-by: Tingfang Bao <bbao@pivotal.io>
=> [Alternative solution] Archive gpdb src with submodules 

CONTRIBUTING.md
Please refer to Greenplum DB which has the same process:
https://github.com/greenplum-db/gpdb/blob/master/.github/CONTRIBUTING.md#direct-commits-to-the-repository
Co-authored-by: Amil Khanzada <akhanzada@pivotal.io>
Co-authored-by: Xin Zhang <xzhang@pivotal.io>
=> Add "Direct commits to the repository" section

ci/concourse/pipelines/gpdb_opensource_release.yml, ci/concourse/scripts/publish_to_ppa.py, ci/concourse/tasks/verify_ppa_release.yml
This PR is a bug fix for release gpdb to PPA. Although we can upload the gpdb deb package to the PPA,  it still maybe reject by the PPA due to some unexpected reasons. Here, add a new job **verify ppa release**.  It can make the rest steps continue to run after releasing to PPA successfully
[#168673847]
=> Verify the PPA release result

ci/concourse/scripts/compile_gpdb_oss.bash
Becasue gporca source codes will be merged into gpdb
source codes repository, here we need to support compiling
gporca in two ways.
1. fetch gporca src from github and compile it.
2. compile it directly if gporca source codes already in gpdb src
repo.
=> Support compiling gporca within gpdb source codes.

ci/concourse/scripts/compile_gpdb_oss.bash
https://github.com/greenplum-db/gpdb/pull/10091 got rid of the
xerces patch we used to apply (this is for master and 6X_STABLE).
Guard against accessing a directory that might no longer exist.
=> Check for existence of xerces patch

ci/concourse/scripts/greenplum-db-6.spec
This commit adds two scriptlets to the greenplum-db-6 RPM spec:
1. `%post` which is executed _after_ the package is installed
2. `%postun` which is executed _after_ the package is uninstalled
The post-install scriptlet force creates a symlink to the directory just
installed by this package. This means, in the case of parallel installs,
that last installed package (regardless of version) will have the
`$PREFIX/greeplum-db` symlink pointing to its directory.
The post-uninstall scriptlet checks if the symlink is pointing at the
directory owned by the package; if it is, it removes it.
[#173347015]
=> Update RPM spec for greenplum-db-6 to create/remove symlink

Makefile, README.md, bin/run_docker_gpdb5_rpm_package.sh
The code for building a GP 5 RPM locally assumed that you had a
tar archive named "bin_gpdb/bin_gpdb.tar.gz" in the current working
directory (i.e., in "greenplum-database-release"). This commit uses the
value of the environment variable BIN_GPDB_TARGZ to determine which tar
archive to build in to an RPM.
If the environment variable is not set or does not point to a regular
file, the code prints an error message and exits.
[#173785658]
Co-authored-by: Brent Doil <bdoil@vmware.com>
Co-authored-by: Bradford D. Boyle <bradfordb@vmware.com>
=> GP 5: Support local RPM builds with BIN_GPDB_TARGZ

ci/concourse/scripts/greenplum-db-6.spec
On centos6, we need libevent2.
On centos7, the default libevent version is 2.x, 
but on centos6 , the default libevent verison is 1.x.
This should be merged after : 
https://github.com/pivotal/gp-image-baking/pull/85
https://github.com/greenplum-db/gpdb/pull/10405
=> Update rpm spec for centos6

Makefile, README.md, bin/create_gpdb5_rpm_package.bash, bin/create_gpdb6_rpm_package.bash, ci/concourse/scripts/greenplum-db-4.spec
- GPDB4.3 RPM package is based on GPDB5 RPM packaging script.
- New `greenplum-db-4.spec` to remove the `Obsoletes` attribute.
- Refactor the make target `local-build-gpdb-rpm` to detect the major version automatically.
=> Add support for GPDB 4.3 RPM packaging

README.md
- Use a standard convention of "Configuration" and "Execution"
- Make it clear when special conditions exist, such as needing `yq`
Co-authored-by: Kris Macoskey <kmacoskey@vmware.com>
=> Adjust README for local package process

Makefile, bin/create_gpdb6_rpm_package.bash, ci/concourse/scripts/greenplum-db-7.spec
- add new greenplum-db-7.spec file
- update Makefile and create_gpdb6_rpm_package.bash to be shared between gpdb6 and gpdb7
=> Support creating Greenplum 7 Server RPM packages locally

Makefile, README.md, ci/concourse/scripts/build_gpdb_deb.bash
- update README to use one make command for gpdb5/6/7 deb package build
- update Makefile and build_gpdb_deb.bash to be shared between gpdb6 and gpdb7
=> Support creating Greenplum 7 Server DEB packages locally

README.md
No functional changes. Only some reorganization of the readme.
If you want to view it without a diff, click here: https://github.com/greenplum-db/greenplum-database-release/blob/kris-reorganize-refactor-readme/README.md
~~I do know that the DEB package behavior doc doesn't exist. This is ok - it's a placeholder.~~
=> Reorganize and refactor readme

ci/concourse/pipelines/gpdb-opensource-release.yml, ci/concourse/tasks/push-to-tanzunet.yml, ci/concourse/vars/greenplum-database-release.dev.yml, ci/concourse/vars/greenplum-database-release.prod.yml
It is because the variable tanzunet-s3-filepath-prefix can be retrieved from the
tanzunet API using product_slug
=> Remove unused variable tanzunet-s3-filepath-prefix

ci/concourse/scripts/greenplum-db-6.spec
- If not available, xerces will fail with error
"Could not load a transcoding service"
=> On Photon glibc-iconv is required to perform transcoding.

ci/concourse/pipelines/gpdb-opensource-release.yml
Since for the open source gpdb, we add prefix 'open-source' for the package
name. So update the resource regexp definition to make them consistent.
=> Update gpdb_rpm_installer_centos6 resource regexp to be clear

ci/concourse/scripts/greenplum-db-6.spec, ci/concourse/scripts/greenplum-db-7.spec
The required packages for the Greenplum 6 & 7 RPM differ significantly between Centos 6/Centos 7 and Photon. This commit better defines the different package requirements in the spec files.
=> [GP-312] Photon RPM dependency updates

ci/concourse/scripts/gpdb-github-release.bash
Fix bug in build_gpdb_binaries_tarball
Also use `git rev-parse HEAD` to get commit SHA
=> Fix bug in build_gpdb_binaries_tarball

ci/concourse/oss/ppa.py, ci/concourse/scripts/build-gpdb-clients-deb.bash, ci/concourse/scripts/build-gpdb-deb.bash, ci/concourse/scripts/compile-gpdb-oss.bash, ci/concourse/scripts/gpdb-clients.spec, ci/concourse/scripts/greenplum-db-5.spec, ci/concourse/scripts/greenplum-db-6.spec, ci/concourse/scripts/greenplum-db-7.spec, ci/concourse/tests/gpdb6/clients/rpm/controls/gpdb6-clients-rpm.rb, ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb, gpdb-deb-test/features/gpdb-client-deb.feature, gpdb-deb-test/features/gpdb-deb.feature, gpdb-deb-test/gpdb-deb_test.go
Move python bytecode compilation to RPM/DEB package postinstall
- Remove bytecode when exporting gpdb tarball
- Compile bytecode:
- As part of RPM install scriptlet
- As part of DEB postinst scriptlet
- Remove bytecode when uninstalling packages.
- Files are registered during RPM install scriptlet, are removed
during normal uninstall
- As part of DEB prerm scriptlet
Add package tests
=> Generate python bytecode when installing packages

ci/concourse/scripts/build-gpdb-clients-deb.bash, ci/concourse/scripts/build-gpdb-deb.bash
dpkg -L "${__package_name}" has two errors here:
First __package_name does not have the correct value we want which is greenplum-db-6, actually its value is: greenplum-db-6.17.1+dev.16.g1c70f219d2-ubuntu18.04-amd64
Second, even we give the __package_name the correct value: greenplum-db-6,   dpkg -L "${__package_name}" still will not work, since the *.pyc files are created by the postinst script, debian does not think the .pyc files should belong to debian package,  so it will not any show the *.pyc file.
=> Fix the prerm script for gpdb debian package

ci/concourse/oss/ppa.py
dpkg -L {self.package_name} will not show any .pyc file, so use find command to list the pyc files
=> Fix the prerm script for gpdb ppa package

ci/concourse/oss/ppa.py, ci/concourse/scripts/build-gpdb-deb.bash, ci/concourse/scripts/greenplum-db-5.spec, ci/concourse/scripts/greenplum-db-6.spec, ci/concourse/scripts/greenplum-db-7.spec, ci/concourse/tests/ppa-test.py
That is because GPHOME is determined automatically in gpdb source
=> Not set GPHOM when packaging

ci/concourse/oss/ppa.py
When the package name was updated from `greenplum-db` to
`greenplum-db-6`, the install prefix continued to use the package name,
resulting in the PPA version to be installed in
`/opt/greenplum-db-6-$version`
=> Change PPA install location to /opt/greenplum-db-$version

ci/concourse/scripts/build-gpdb-rpm.py
Set to bin_gpdb.tar.gz to ensure we always pick up the correct tarball
if multiple are present in the bin_gpdb folder
Co-authored-by: Brent Doil <bdoil@vmware.com>
Co-authored-by: Bhanu Kiran Atturu <batturu@vmware.com>
=> Remove * glob when setting bin_gpdb_path

ci/concourse/scripts/build-gpdb-deb.bash, gpdb-deb-test/gpdb-deb_test.go
due to https://github.com/greenplum-db/gpdb/commit/b9a2acec5956ab5a2288757d7bc9d8bb52622d8f
when source GPHOME from link, it will show GPHOME=greenplum-db while we expect it
GPHOME=/usr/local/greenplum-db
=> Create link with full path

ci/concourse/scripts/test-package-dependencies.bash
Or else pythonhome is set to python2, and will see error
+ subscription-manager remove --all
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
=> call subsription-manager before greenplum-path.sh

ci/concourse/pipelines/gpdb-opensource-release.yml
So git concourse resource can checkout to tags that is not on 6X_STABLE
=> Remove branch for gpdb_src defination

ci/concourse/tasks/build-gpdb-clients-msi.yml
Since we are compiling windows clients in gp-compile, the artifact name changed
=> Fix bug in windows task yml

Makefile
Since the pipeline is not paused for existing prod pipeline, so the
message is invalid
=> Remove confusing message

ci/concourse/pipelines/gpdb-opensource-release.yml
=> Use github-token-gp-releng instead of gpdb-release-access-token

Greenplum-Server-RPM-Packaging-Specification.md
When doing a Greenplum 5 to Greenplum 6 upgrade, the current behavior
would change the /usr/local/greenplum-db symlink to Greenplum 6 before
the user is ready.
This is a change in behavior such that the user has control over when
the symlink points to Greenplum 6 when they are currently using
Greenplum 5.
=> Updated specification for symlink behavior

ci/concourse/scripts/verify_gpdb_versions.bash
This fails in the releng concourse and I dont think we need it.
Authored-by: Karen Huddleston <khuddleston@vmware.com>
=> Remove yum install for git

Makefile, ci/concourse/pipelines/gpdb-opensource-release.yml
Previosuly, the resources always fetches the latest OSL/ODP.
=> Use GPDB minor verison for fetching the OSL and ODP files.

ci/concourse/scripts/verify_gpdb_versions.bash
bin_gpdb_centos8 should be renamed to bin_gpdb_rhel8.
=> Fix verify_version step.

ci/concourse/scripts/gpdb-7-clients.spec, ci/concourse/scripts/gpdb-clients.spec, ci/concourse/scripts/greenplum-db-6.spec, ci/concourse/scripts/greenplum-db-7.spec
install gpdb server rhel8 rpm on gpdb6-rhel8-build image will cause fowllowing errors
Error: Transaction test error file /usr/lib/.build-id/e2/27e93b07fbc71d773fa0bb847faba619639bb4 from install of greenplum-db-6-6.20.0-1.el8.x86_64 conflicts with file from package libquicklz-1.5.0-1.el8.x86_64 file /usr/lib/.build-id/e1/912a5ed956a4243112da62fc86e62cc0176512 from install of greenplum-db-6-6.20.0-1.el8.x86_64 conflicts with file from package libzstd-1.3.7-2.el8.x86_64
So disable build_id_links to bypass the error
[GPR-747]
=> Disalbe _build_id_links

ci/concourse/pipelines/gpdb-package-testing.yml, ci/concourse/scripts/test-functionality-rpm.bash, ci/concourse/tasks/test-functionality-rpm.yml, ci/concourse/tests/gpdb6/server/conflicts/gpdb6-server-conflicts.rb, ci/concourse/tests/gpdb6/server/upgrade/controls/gpdb6-server-upgrade.rb, ci/concourse/tests/gpdb7/server/conflicts/gpdb7-server-conflicts.rb, ci/concourse/tests/gpdb7/server/upgrade/controls/gpdb7-server-upgrade.rb
Change previous 6.12.0 to 6.20.0 since that's the oldest release with rhel8 rpm on TanzuNet.
[GPR-748]
=> Increase test coverage for rhel8.

ci/concourse/scripts/greenplum-db-6.spec
In 6.22 release, we introduce python39 to Greenplum. When packing the rpm package, we compiling python scripts to .pyc bytecode files. However, the compilation steps is using a python2 interpreter which is unable to compile python3.9 scripts. On the other hand, python3.9 scripts have been compiled to bytecode files, we don't need to compile them again.
Co-authored-by: Hao Zhang <hzhang2@vmware.com>
Co-authored-by: Xing Guo <higuoxing@gmail.com>
=> Don't compile python3.9 scripts when packaging rpm.

ci/concourse/scripts/build-gpdb-deb.bash
We ship Python 3.9 with Greenplum database to enterprise users. We encountered errors when compiling Python 3.9 scripts during post installation. Actually, we don't want to compile them in this release. This patch fixes the issue temporarily, we need to re-consider how to integrate Python 3.9 better in future release.
=> Fix post installation script for debian package (Temporarily).

ci/concourse/scripts/compile-gpdb-oss.bash
Since we integrate python3.9 to gpdb6 and the build image for rhel8/centos7/ubuntu18.04 will include two version python, we need to use correct command to get the PYTHONHOME.
[GPR-1035]
Co-authored-by: Hao Zhang <hzhang2@vmware.com>
=> Fix PYTHONHOME to correct location

ci/concourse/scripts/test-package-dependencies.bash
Python2.7 dependency is also ingored.
[GPR-1044]
=> Ignore python3.9 dependency

.gitignore, Makefile, ci/concourse/pipelines/gpdb-package-testing.yml
Since we integrate python3.9 for gpdb6 in the 6X-release pipeline then create the installer rpm, but the output rpm package has never been tested, so it caused the install gpdb failed before. Refer to the story https://jira.eng.vmware.com/browse/GPR-1025.
This commit will add the integrate components job before create rpm installer jobs in order to test the integrated components not broke the package installation behavior.
=> Add integrate components job to gpdb-package-testing pipeline

ci/concourse/scripts/test-package-dependencies.bash
So user do not need to install xerces-c by themselves.
[GPR-1016]
Co-authored-by: Lucas Bonner <blucas@vmware.com>
=> Xerces-c will be provided by us

ci/concourse/scripts/test-package-dependencies.bash
Adds a command to remove /etc/rhsm-host for rhel8 in order to bypass the subscription manager failure in the container
[GPR-1101]
Co-authored-by: Lucas Bonner <blucas@vmware.com>
=> Subscription manager fix for gpdb-package-testing

ci/concourse/pipelines/gpdb-package-testing.yml
Currently we do not have binary for gpdb7 rocky8, so use binary for gpdb7 rhel8 to make the pipeline run.
=> Use rhel8 gpdb binary

ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb
Upgraded from Python 2.7.17 to 2.7.18 & therefore also need a test change
=> Fix for the test_functionality_gpdb6_rpm_rhel8 

ci/concourse/scripts/verify_gpdb_versions.bash
for gpdb7, it only has the dir bin_gpdb_rhel8, so need to test if the dir exist
=> verify_gpdb_versions.bash to support gpdb7

ci/concourse/scripts/test-package-dependencies.bash
subscription-manager register will fail with 1, and it cause subscription-manager attach not run. the failure does not matter, since it is just unsubscrip status like following, after subscription-manager attach it will be subscip status.
The system has been registered with ID: XXXX
The registered system name is: XXXX
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux for x86_64
Status:       Not Subscribed
[GPR-1174]
=> Fix subscription-manager register failure

ci/concourse/oss/rpmbuild.py, ci/concourse/pipelines/gpdb-package-testing.yml, ci/concourse/scripts/greenplum-db-6.spec, ci/concourse/scripts/test-functionality-rpm.bash, ci/concourse/tests/gpdb6/server/upgrade/controls/gpdb6-server-upgrade.rb
Also add oel8 for gpdb6 spec file, it should be same as rhel8 and rocky8
[GPR-1090]
=> Add support for oel7

ci/concourse/scripts/greenplum-db-6.spec
- libcgroup-tools will be required dependency on RHEL7/8
- libcgroup will be required dependency on RHEL6
[GPR-1193]
=> Add required package for resource group for GPDB6

ci/concourse/oss/rpmbuild.py, ci/concourse/pipelines/gpdb-package-testing.yml, ci/concourse/pipelines/gpdb7-opensource-release.yml, ci/concourse/scripts/build-gpdb-clients-rpm.sh, ci/concourse/scripts/test-clients-functionality.sh, ci/concourse/scripts/test-functionality-rpm.bash, ci/concourse/tests/gpdb7/server/upgrade/controls/gpdb7-server-upgrade.rb
For greenplum-database-release-7 pipeline:
- replace gpdb7-rhel8-build with gpdb7-rocky8-build image, and change the file name from rhel8 to el8
For gpdb-package-testing pipeline:
- remove the job create_gpdb7_rpm_installer_oel8 and create_gpdb7_rpm_installer_rhel8
- remove the job create_gpdb7_rpm_installer_oel8_oss and create_gpdb7_rpm_installer_rhel8_oss
- remove the job create_gpdb7_clients_rpm_installer_oel8 and create_gpdb7_clients_rpm_installer_rhel8
- update the resource bin_gpdb7_rocky8 and bin_gpdb7_clients_rocky8 file name to el8
- update the gpdb7 rpm file name to el8
[GPR-1228]
=> Update GPDB7 OSS release pipeline

ci/concourse/pipelines/gpdb-package-testing.yml, ci/concourse/scripts/greenplum-db-7.spec, ci/concourse/scripts/test-functionality-rpm.bash, ci/concourse/tasks/test-functionality-rpm.yml, ci/concourse/tests/gpdb7/server/conflicts/gpdb7-server-conflicts.rb, ci/concourse/tests/gpdb7/server/upgrade/controls/gpdb7-server-upgrade.rb, ci/concourse/vars/gpdb-package-testing.dev.yml, ci/concourse/vars/gpdb-package-testing.prod.yml
Fix the undefined var gpdb_major_version. It cause when upgrade gpdb7 from previous version, the link greenplum-db did not point to the new gpdb7 rpm version
When previous-7.0.0-beta.0-release installed, then intall current gpdb7 version rpm, it will automatically remove the 7.0.0-beta.0 rpm, and upgrade to current gpdb7 version rpm
When install previous-7.0.0-beta.0-oss-release first, then install current gpdb7 version rpm, it will conflict
When install previous-7.0.0-beta.0-release first, then install current gpdb7 oss version rpm, it will also confict
[GPR-1059]
=> Add upgrade and conflict test for gpdb7

Makefile, ci/concourse/pipelines/gpdb-package-testing.yml
the gpdb-package-testing-HEAD-root is created when set dev pipeline for gpdb-package-testing, in concourse tasks, the branch and user name is settting to HEAD and root.
To prevent is being created, make DEV_GPDB_PACKAGE_TESTING_PIPELINE_NAME can be set by user if not set, so we can pass it when fly pipeline
[GPR-1282]
=> Prevent create gpdb-package-testing-HEAD-root

ci/concourse/oss/rpmbuild.py
For the three platforms rhel8, rocky8 and oel8, we want the name suffix to be rhel8 for gpdb6 and el8 for gpdb7, since the operator precedence in Python `and` has more higher precedence than `or`, that will cause the logic go to wrong section which lead the filename suffix to be el8 for gpdb6.
=> Fix the filename wrong when building rpm for gpdb6 on rhel8

ci/concourse/oss/base.py, ci/concourse/oss/rpmbuild.py, ci/concourse/tasks/build-gpdb-rpm.yml
The `gpdb_version_short` is the full version (e.g 7.99.99), should use the major version to check. 
[GPR-1301]
=> Fix the rpm filename wrong for gpdb7

ci/concourse/scripts/build-gpdb-clients-deb.bash
"build-gpdb-clients-deb.bash" was not set up to handle versions like "6.99.99" or "7.99.99", now it will.
[GPR-1386]
=> Fix create_gpdb_clients_deb_installer_ubuntu18.04

ci/concourse/scripts/greenplum-db-7.spec
From beta4, the management utilities depend on the system default
python3, which is python3.6 for el8; plpython depends on the python3.9.
So both of them need to be in the dependencies list.
https://jira.eng.vmware.com/projects/GPEX/issues/GPEX-95?filter=allopenissues
=> Add python3 to GP7 RPM dependencies

ci/concourse/scripts/gpdb-7-clients.spec, ci/concourse/scripts/greenplum-db-7-clients-control, ci/concourse/scripts/greenplum-db-7-control, ci/concourse/scripts/greenplum-db-7.spec
We're replacing pygresql with psycopg2 for gpdb7, since many OS provide psycopg2 in their systems' package managers. We don't need to vendor it ourselves. This patch helps add python3-psycopg2 as dependencies of rpm installer and deb installer.
Relevant PR:
- https://github.com/greenplum-db/gpdb/pull/15988
- https://github.com/greenplum-db/gpdb/pull/16001
=> Add python3-psycopg2 as a dependency for gpdb7 and its clients.

ci/concourse/scripts/greenplum-db-6.spec
On EL9, system provided rsync and our built libzstd 1.3.7 is not compatible, it will error like:
/bin/rsync: undefined symbol: ZSTD_compressStream2
So we unvendor our bulit libzstd 1.3.7 for gpdb6, and require system provided libzstd instead
=> Use system provided libzstd on EL9

ci/concourse/scripts/greenplum-db-7.spec
=> Remove llvm-libs as required as it is now vendored

ci/concourse/scripts/test-package-dependencies.bash
=> Adding temporary ignore LLVM until vendored for GP7

ci/concourse/scripts/greenplum-db-6.spec
So remove the libicu-devel for gpdb6 EL9
=> xerces 3.1.2 on EL9 has dropped deps for libicu

ci/concourse/scripts/gpdb-7-clients.spec
=> Adding compat-openssl11 for el9 clients to fix missing libssl dependency
