Makefile

Change default Concourse target to releng

---

concourse/scripts/build_gpdb_deb.bash

When building the deb, we can get the Greenplum version from gpdb_src
or from the contents of `etc/git-info.json` in the bin_gpdb tarball.
This commit adds functionality to read the version from `git-info.json`
when gpdb_src does not exist.
Dev: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-get_bin_version-sbai

Add function to get version from binary

---

concourse/pipelines/gpdb_opensource_release.yml
concourse/scripts/build_gpdb_rpm.bash
concourse/scripts/greenplum-db.spec
concourse/tasks/build_gpdb_deb.yml
concourse/tasks/build_gpdb_rpm.yml

dev pipeline: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/greenplum-database-release-rpm-sbai

Prebuilt binaries of Open Source Greenplum 6 Database Server as an RPM in the Github Release

---

concourse/scripts/build_gpdb_rpm.bash
concourse/scripts/greenplum-db.spec
concourse/tasks/build_gpdb_rpm.yml

Add missing Copyright headers

---

Makefile
concourse/pipelines/gpdb_opensource_release.yml
concourse/scripts/build_gpdb_deb.bash
concourse/scripts/build_gpdb_rpm.bash
concourse/scripts/compile_gpdb_oss.bash
concourse/scripts/gpdb_github_release.bash
concourse/scripts/greenplum-db.spec
concourse/tasks/build_gpdb_deb.yml
concourse/tasks/build_gpdb_rpm.yml
concourse/tasks/compile_gpdb_oss.yml
concourse/tasks/gpdb_github_release.yml

Replace errant utf-8 character in copyright

---

concourse/oss/rpmbuild.py
concourse/scripts/build_gpdb_deb.bash

Use different osl filename for OSS gpdb and Pivotal gpdb

---

concourse/scripts/compile_gpdb_oss.bash

Add '--disable-debug-extensions' option

---

concourse/pipelines/gpdb_opensource_release.yml

Update oss gpdb osl file

---

concourse/oss/ppa.py
concourse/tests/ppa_test.py

Replace the '-' with '~' in DEB version

---

concourse/pipelines/gpdb_opensource_release.yml

Update the python artifact path

---

Makefile

Fix paths for Concourse pipeline in Makefile

---

ci/concourse/scripts/compile_gpdb_oss.bash

Disable the TAP tests

---

ci/concourse/pipelines/gpdb_opensource_release.yml

Add the triggers for pushing ppa and github release jobs

---

.yamllint
ci/concourse/scripts/gpdb_github_release.bash

Archive the gpdb src codes with submodules

---

Makefile
ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Co-authored-by: Ning Wu <nwu@pivotal.io>
Co-authored-by: Shaoqi Bai <sbai@pivotal.io>

Move non-secrets out of gp-continuous-integration for greenplum-database-release

---

Greenplum-Server-RPM-Packaging-Specification.md
README.md

- A basic description
- The current RPM packaging specification

Add initial content for the README

---

ci/concourse/oss/rpmbuild.py
ci/concourse/scripts/build_gpdb_rpm.py
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/tests/build_gpdb_rpm_test.py

Authored-by: Shaoqi Bai <sbai@pivotal.io>

Greenplum 6 Server RPM package follows new Packaging Layer behavior

---

Greenplum-Server-RPM-Packaging-Specification.md

Update RPM packaging spec for patchelf exception

---

Greenplum-Server-RPM-Packaging-Specification.md

Document additional patchelf exception for krb5

---

Greenplum-Server-RPM-Packaging-Specification.md

Various updates for clarity and one functional change regarding symbolic links

RPM Documentation updates and changes

---

NOTICE

Update NOTICE file

---

ci/concourse/pipelines/gpdb_opensource_release.yml

Add Slack notifictions for job failures

---

ci/concourse/scripts/build_gpdb_deb.bash
ci/concourse/scripts/publish_to_ppa.py
ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Rename Debian package to greenplum-db-6

---

CODE-OF-CONDUCT.md

add CODE-OF-CONDUCT.md

---

ci/concourse/scripts/build_gpdb5_rpm.sh
ci/concourse/scripts/greenplum-db-5.spec
ci/concourse/tasks/build_gpdb5_rpm.yml
ci/concourse/tasks/build_gpdb5_rpm_sles.yml

[#173480287]
Authored-by: Tingfang Bao <baotingfang@gmail.com>

Add build gpdb5 rpm concourse tasks

---

ci/concourse/scripts/greenplum-db-5.spec
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/scripts/greenplum-db.spec

[#173481689]
Authored-by: Tingfang Bao <baotingfang@gmail.com>

Only force symlink creation when overwriting a symlink

---

ci/concourse/pipelines/gpdb_opensource_release.yml

Fix RPM package name in pipeline

---

README.md

Add instruction for pipeline setup

---

ci/concourse/oss/rpmbuild.py
ci/concourse/scripts/build_gpdb_deb.bash

GP 6: change osl file name for both deb and rpm

---

greenplum-db-5/debian/control

GP 5: update debian maintainer email to release@greenplum.org

---

GOVERNANCE.md
MAINTAINERS.md

Add MAINTAINERS file to greenplum-database-release

---

ci/concourse/scripts/compile_gpdb_oss.bash

Greenplum Database 6 Server distribution shows "Open Source" in version string

---

ci/concourse/vars/greenplum-database-release.prod.yml

Update debian release docs url

---

README.md

Add instructions of building RPM package in a concourse pipeline

---

README.md

Add instruction to build Debian package in concourse

---

bin/create_gpdb5_deb_package.bash

The change is in https://github.com/pivotal/gp-release/pull/443

Update gpdb5 concourse variable file name

---

ci/concourse/scripts/compile_gpdb_oss.bash

Limit make parallelism to -j 4

---

.gitignore
Makefile
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/test_functionality_rpm.sh
ci/concourse/tasks/test_functionality_rpm.yml
ci/concourse/tasks/test_functionality_rpm_sles.yml
ci/concourse/tests/gpdb_centos_install/controls/gpdb_centos_install.rb
ci/concourse/tests/gpdb_centos_install/inspec.yml
ci/concourse/tests/gpdb_centos_remove/controls/gpdb_centos_remove.rb
ci/concourse/tests/gpdb_centos_remove/inspec.yml
ci/concourse/tests/gpdb_generic_rpm/controls/gpdb_generic_rpm.rb
ci/concourse/tests/gpdb_generic_rpm/inspec.yml
ci/concourse/tests/gpdb_installed/controls/gpdb_installed.rb
ci/concourse/tests/gpdb_installed/inspec.yml
ci/concourse/tests/gpdb_sles_install/controls/gpdb_sles_install.rb
ci/concourse/tests/gpdb_sles_install/inspec.yml
ci/concourse/tests/gpdb_sles_remove/controls/gpdb_sles_remove.rb
ci/concourse/tests/gpdb_sles_remove/inspec.yml
ci/concourse/tests/greenplum-db-5-rpm/controls/greenplum-db-5-rpm.rb
ci/concourse/vars/gpdb-package-testing.dev.yml
ci/concourse/vars/gpdb-package-testing.prod.yml

This will test the packaging and content of the RPM packages. It will
also go through few scenarios like install, remove, upgrade, etc.
Co-authored-by: Brent Doil <bdoil@vmware.com>
Co-authored-by: Xin Zhang <zhxin@vmware.com>

Adding gpdb-package-testing pipeline

---

Makefile

Co-authored-by: Xin Zhang <zhxin@vmware.com>

Add set-gpdb-package-testing-prod pipeline make target

---

Greenplum-Server-RPM-Packaging-Specification.md
MAINTAINERS.md
Makefile
ci/concourse/vars/gpdb-package-testing.prod.yml
ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Update default branch to main

---

.github/workflows/code-style-check.yml
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/pipelines/gpdb_opensource_release.yml
ci/concourse/scripts/push_to_tanzunet.bash
ci/concourse/tasks/push_to_tanzunet.yml
ci/concourse/tests/greenplum-db-5-rpm/controls/greenplum-db-5-rpm.rb
ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml
ci/gpdb6/concourse/pipelines/gpdb6-package-testing.yml
ci/gpdb6/concourse/tests/gpdb_generic_rpm/controls/gpdb_generic_rpm.rb
ci/gpdb6/concourse/tests/greenplum-db-6-rpm/controls/greenplum-db-6-rpm.rb

Rename tanzunet-client-git-remote target

---

ci/concourse/pipelines/gpdb_opensource_release.yml
ci/concourse/scripts/push_to_tanzunet.bash

So there is no need to make build everytime

Get tanzunet_client from github release

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/scripts/compile-gpdb-oss.bash
ci/concourse/tasks/compile-gpdb-oss.yml

Make compile prefix same with deb/rpm prefix

---

ci/concourse/pipelines/gpdb-opensource-release.yml

Update pipeline input

---

ci/concourse/scripts/build-gpdb-deb.bash

Add iputils-ping, locales as deb dependencies

---

ci/concourse/scripts/test-functionality-rpm.bash
ci/concourse/tests/gpdb5-generic-rpm/controls/gpdb5-generic-rpm.rb
ci/concourse/tests/gpdb5-installed/controls/gpdb5-installed.rb
ci/concourse/tests/gpdb6-generic-rpm/controls/gpdb6-generic-rpm.rb
ci/concourse/tests/greenplum-db-6-rpm/controls/greenplum-db-6-rpm.rb

Fix pipeline failures for gpdb-package-testing

---

Makefile

Change pipelinename to better name

---

ci/concourse/vars/greenplum-database-release.prod.yml

Switch to greenplum-database in product slug

---

ci/concourse/oss/rpmbuild.py
ci/concourse/scripts/greenplum-db-6.spec

GPDBVT includes "open-source" in the file names and package names

---

ci/concourse/pipelines/gpdb-opensource-release.yml

Fix the prod pipleline failure

---

ci/concourse/pipelines/gpdb-opensource-release.yml

GPDBVT Releases available to All Users by default

---

ci/concourse/pipelines/gpdb-package-testing.yml

file path
'greenplum-database-release/ci/concourse/tasks/test-clients-functionality.yml'

Fix unknown artifact source: 'greenplum-database-release' in task config

---

ci/concourse/oss/rpmbuild.py
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/scripts/greenplum-db-7.spec

Pass PLATFORM to spec files.

---

ci/concourse/vars/greenplum-database-release.prod.yml

Bump tanzunet client version to 4.3.1

---

ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Change to prod instance of Tanzunet

---

Greenplum-Server-RPM-Packaging-Specification.md
README.md
bin/create_gpdb5_rpm_package.bash
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/gpdb-clients.spec
ci/concourse/tasks/build-gpdb-clients-deb.yml
ci/concourse/tasks/build-gpdb-clients-rpm.yml
ci/concourse/tasks/build-gpdb5-rpm-sles.yml
ci/concourse/tests/gpdb5/server/greenplum-db-5/controls/greenplum-db-5-rpm.rb
ci/concourse/tests/gpdb6/clients/deb/controls/gpdb6-clients-deb.rb
ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb
ci/concourse/vars/gpdb-package-testing.prod.yml

Change pivotal.io to tanzu.vmware.com

---

ci/concourse/scripts/gpdb-github-release.bash

Save VERSION file in source tarball.

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/scripts/compile-gpdb-oss.bash
ci/concourse/tasks/compile-gpdb-oss.yml

Refactor compile OSS script and remove unneeded python resource.

---

bin/create_gpdb5_rpm_package.bash
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/gpdb-clients.spec
ci/concourse/scripts/push-to-tanzunet.bash
ci/concourse/tasks/build-gpdb-clients-deb.yml
ci/concourse/tasks/build-gpdb-clients-rpm.yml
ci/concourse/tasks/build-gpdb5-rpm-sles.yml
ci/concourse/tests/gpdb5/server/greenplum-db-5/controls/greenplum-db-5-rpm.rb
ci/concourse/tests/gpdb6/clients/deb/controls/gpdb6-clients-deb.rb
ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb

Rename pivotal-gpdb Tanuznet slug to vmware-tanzu-greenplum

---

ci/tanzunet/metadata.yml

Updating Export Classification for future releases.

Update ECCN and License Exception

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb-package-testing.yml

Use from gcr instead of dockerhub

---

ci/concourse/vars/greenplum-database-release.prod.yml

Upgrade tanzunet-client-version

---

ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/scripts/greenplum-db-7.spec

RHEL7 requires libevent

---

ci/concourse/scripts/compile-gpdb-oss.bash

No longer required to build/install xerces-c when using
gpdb6-build container images.
xerces-c, zstd are installed in /usr/local/lib64
install_python is smarter about finding the vendored python in /opt

Gp 552 vendored deps usr local

---

ci/concourse/pipelines/gpdb-opensource-release.yml

Use correct ODP file for OSS release

---

ci/concourse/vars/greenplum-database-release.prod.yml

Bump tanzunet client version to v4.4.1

---

ci/tanzunet/metadata.yml

Fix typo in OSS release filegroup on TanzuNet metadata yml

---

Makefile

Use gp-releng-dev@pivotal.io TanzuNet account for dev pipelines.

---

ci/concourse/vars/greenplum-database-release.prod.yml

Bump tanzunet client version

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/tasks/check-version.yml
ci/concourse/vars/greenplum-database-release.prod.yml

trigger it when the release becomes available to all users on TanzuNet
[GP-676]

Change the greenplum-database-release pipeline trigger condition

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/tasks/generate-start-messages-oss.yml

Send slack message when start the greenplum-database-release pipeline

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/tasks/check-version.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Remove fetching greenplum-database-release commit using tag

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/CentOS6.10-Vault.repo
ci/concourse/scripts/build-gpdb-clients-deb.bash
ci/concourse/scripts/test-package-dependencies.bash
ci/concourse/tasks/test-package-dependencies.yml

Add test to check if RPM/DEB packages resolve all needed dependencies.

---

ci/concourse/vars/greenplum-database-release.prod.yml

Bump tanzuent client version

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/tasks/check-version.yml
ci/concourse/tasks/push-to-tanzunet.yml

Update docker container to golang 1.16-buster

---

ci/concourse/vars/greenplum-database-release.prod.yml

Bump tanzunet client version to v4.5.2

---

ci/concourse/scripts/compile-gpdb-oss.bash

Change greenplum_install_dir for ppa to greenplum-db-${GPDB_VERSION}

---

ci/concourse/pipelines/gpdb-package-testing.yml

Add groups to easy find jobs

---

ci/concourse/pipelines/gpdb-package-testing.yml

Trigger by release candidates

---

Makefile

Use FLY_OPTION_NON_INTERACTIVE if set in env

---

Makefile

Fetch the correct resource of gpdb repo in dev pipeline

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-deb.bash
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/gpdb-7-clients.spec
ci/concourse/scripts/greenplum-db-7-clients-control
ci/concourse/scripts/greenplum-db-7.spec
ci/concourse/scripts/retrieve-gpdb-src.bash
ci/concourse/scripts/test-clients-functionality.sh
ci/concourse/scripts/test-functionality-rpm.bash
ci/concourse/scripts/test-package-dependencies.bash
ci/concourse/tasks/build-gpdb-clients-deb.yml
ci/concourse/tasks/build-gpdb-clients-rpm.yml
ci/concourse/tasks/retrieve-gpdb-src.yml
ci/concourse/tasks/test-clients-functionality.yml
ci/concourse/tests/gpdb7/clients/rpm/controls/gpdb7-clients-rpm.rb
ci/concourse/tests/gpdb7/server/conflicts/gpdb7-server-conflicts.rb
ci/concourse/tests/gpdb7/server/install/controls/gpdb7-server-install.rb
ci/concourse/tests/gpdb7/server/remove/controls/gpdb7-server-remove.rb
ci/concourse/tests/gpdb7/server/upgrade/controls/gpdb7-server-upgrade.rb
gpdb-deb-test/gpdb-deb_test.go

Add gpdb7 packages build and test jobs

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/scripts/push-to-tanzunet.bash
ci/concourse/tasks/push-to-tanzunet.yml
ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Create dry run release process for gpdb6

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/tasks/push-to-tanzunet.yml

Upgrade go version to 1.17.6.

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/tasks/push-to-tanzunet.yml

Save golang version in a variable for easier changes

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml

Move greenplum-database-release pipeline to new Concourse.

---

ci/concourse/scripts/CentOS6.10-Vault.repo
ci/concourse/scripts/test-package-dependencies.bash

Update centos6 repo to stable one

---

ci/concourse/scripts/greenplum-db-7.spec

Add libcgroup to GPDB7 rhel8 spec.

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/scripts/verify_gpdb_versions.bash
ci/concourse/tasks/push-to-tanzunet.yml
ci/tanzunet/metadata.yml

Add rhel8 packaging/distribution to greenplum-database release pipeline

---

ci/concourse/pipelines/gpdb-package-testing.yml

Add trigger condition on rhel8 tarball to the packaging jobs.

---

gpdb-deb-test/go.mod
gpdb-deb-test/go.sum

refer: https://github.com/greenplum-db/greenplum-database-release/security/dependabot/2
[GPR-851]

Fix unhandled exception in gopkg.in/yaml.v3

---

Makefile
ci/concourse/pipelines/gpdb-package-testing.yml

Move pipeline gpdb-package-testing secrets to vault

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/test-functionality-deb.bash
ci/concourse/tasks/test-functionality-deb.yml
gpdb-deb-test/features/gpdb-deb.feature
gpdb-deb-test/features/gpdb-ppa.feature
gpdb-deb-test/gpdb-deb_test.go

Add upgrade test for debian package
[GPR-1029]

Add test coverage for enterprise package testing

---

ci/concourse/pipelines/gpdb-package-testing.yml

[GPR-1099]
Co-authored-by: Lucas Bonner <blucas@vmware.com>

Remove centos7 & ubuntu18 from gpdb7

---

Makefile
ci/concourse/pipelines/gpdb-package-testing.yml

It will set the prod gpdb-package-testing in dev pipeline
[GPR-1109]
Co-authored-by: Lucas Bonner <blucas@vmware.com>

Fix the gpdb-package-testing dev pipeline

---

ci/concourse/oss/rpmbuild.py
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/greenplum-db-7.spec

Support Oracle Linux 8 for GPDB7

---

ci/concourse/scripts/greenplum-db-7.spec

Add required dependency for JIT feature

---

ci/concourse/scripts/gpdb-7-clients.spec
ci/concourse/scripts/greenplum-db-7.spec
ci/concourse/scripts/test-package-dependencies.bash

Replaces devel packages in greenplum-db-7.spec file

---

ci/concourse/scripts/compile-gpdb7-oss.bash

Compile gpdb7 for open source

---

Makefile
ci/concourse/pipelines/gpdb7-opensource-release.yml
ci/concourse/vars/greenplum-database-release-7.dev.yml
ci/concourse/vars/greenplum-database-release-7.prod.yml

Set up GP7 open source release pipeline

---

ci/concourse/scripts/compile-gpdb-oss.bash

Only update PATH when PYTHONHOME39 not null

---

ci/concourse/scripts/greenplum-db-6-control
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/scripts/greenplum-db-7-control
ci/concourse/scripts/greenplum-db-7.spec

Co-authored-by: Chen Mulong <chenmulong@gmail.com>

Add required uuid dependency for gpdb6 and gpdb7 packages

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/test-clients-functionality.sh
ci/concourse/scripts/test-functionality-rpm.bash
ci/concourse/scripts/test-package-dependencies.bash

Add OEL8 platform for gpdb-package-testing pipeline

---

ci/concourse/scripts/build-gpdb-deb.bash
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb
gpdb-deb-test/gpdb-deb_test.go

Simplify the generating pyc file for python3.9

---

ci/concourse/scripts/greenplum-db-7.spec

Not use the fixed version of LLVM

---

ci/concourse/scripts/compile-gpdb-oss.bash
ci/concourse/scripts/compile-gpdb7-oss.bash

Fix missing python libraries for opensource build

---

ci/concourse/scripts/compile-gpdb-oss.bash
ci/concourse/scripts/compile-gpdb7-oss.bash

[GPR-1131]
Co-authored-by: Anusha Shakarad <shakarada@vmware.com>

Enable uuid in open source gpdb6 and gpdb7 compilation

---

ci/concourse/pipelines/gpdb7-opensource-release.yml

Update the greenplum database osl for gpdb7

---

ci/concourse/scripts/compile-gpdb7-oss.bash

[GPR-1127]
Co-authored-by: Anusha Shakarad <shakarada@vmware.com>

Adding option --with-llvm to enable JIT for open source GP7.

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/scripts/test-functionality-rpm.bash
ci/concourse/tests/gpdb6/server/conflicts/gpdb6-server-conflicts.rb
ci/concourse/tests/gpdb6/server/upgrade/controls/gpdb6-server-upgrade.rb

Add gpdb6 rocky8 jobs on gpdb-package-testing pipeline

---

ci/concourse/pipelines/gpdb7-opensource-release.yml
ci/concourse/tasks/generate-start-messages-oss.yml
ci/concourse/tasks/send_notification.yml

Also send finished message to vmware/gp-releng channel
[GPR-1221]

Send notification to greenplum/general channel for gpdb7

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb7-opensource-release.yml

to filter the build number
[GPR-1222]

Update the open source release pipeline gpdb binary file name

---

ci/concourse/pipelines/gpdb-package-testing.yml

Move gpdb-package-testing to new ci

---

ci/tanzunet/metadata.yml

Rebrand to VMware Greenplum

---

bin/create_gpdb5_rpm_package.bash
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/gpdb-7-clients.spec
ci/concourse/scripts/gpdb-clients.spec
ci/concourse/scripts/greenplum-db-7-clients-control
ci/concourse/scripts/greenplum-db-clients-control
ci/concourse/scripts/push-to-tanzunet.bash
ci/concourse/tasks/build-gpdb-clients-rpm.yml
ci/concourse/tests/gpdb5/server/greenplum-db-5/controls/greenplum-db-5-rpm.rb
ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb
ci/concourse/tests/gpdb7/server/install/controls/gpdb7-server-install.rb
ci/concourse/vars/greenplum-database-release-7.prod.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Update slug after rebrand

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/tanzunet/metadata.yml

Remove the tanzu word from gpdb6 osl and odp filename

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/test-functionality-rpm.bash
ci/concourse/tasks/test-functionality-rpm-sles.yml
ci/concourse/tasks/test-functionality-rpm.yml
ci/concourse/tests/gpdb5/server/greenplum-db-5/controls/greenplum-db-5-rpm.rb
ci/concourse/tests/gpdb6/server/conflicts/gpdb6-server-conflicts.rb
ci/concourse/tests/gpdb6/server/upgrade/controls/gpdb6-server-upgrade.rb

Improving gpdb6 test coverage on gpdb-package-testing for rocky8 & oel8

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb7-opensource-release.yml

- greenplum-database-release
- greenplum-database-release-7
[GPR-1254]

Move gpdb open source release pipelines from release to releng concourse

---

ci/concourse/oss/rpmbuild.py
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/build-gpdb-rpm.py
ci/concourse/scripts/test-clients-functionality.sh
ci/concourse/scripts/test-functionality-rpm.bash
ci/tanzunet/metadata.yml

Rolling back file name changes from el8 to rhel8

---

ci/concourse/pipelines/gpdb-opensource-release.yml

Fixup 86075ec30ca09a9ebfd11a50046a8b048b90b0ee

---

ci/concourse/pipelines/gpdb-package-testing.yml

Fix resource for gpdb_component_packaging_rocky8

---

ci/concourse/tasks/generate-start-messages-oss.yml

[GPR-1360]
Authored-by: Mounika M <mmounika@vmware.com>

Update slack message logo to VMware Data Solutions

---

ci/concourse/oss/rpmbuild.py
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/test-clients-functionality.sh

Also cleanup resource that are not used.

Create and test rpm for gpdb7 clients rhel9 

---

ci/concourse/oss/rpmbuild.py

Fix typo in rpmbuild.py

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/gpdb-clients.spec

Create and test rpm for gpdb6 clients rhel9

---

Makefile
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/test-clients-functionality.sh

Add test_functionality_clients_gpdb6_rpm_oel9 job

---

ci/concourse/pipelines/gpdb-package-testing.yml

Fix wrong ENV for test_functionality_clients_gpdb6_rpm_oel9

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/tasks/build-gpdb-rpm.yml

Adding rocky9 ssupport to gpdb6

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb7-opensource-release.yml

Also change +dev to -dev in open source release pipeline

Remove check-creds

---

ci/concourse/oss/rpmbuild.py
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/scripts/build-gpdb-clients-rpm.sh
ci/concourse/scripts/greenplum-db-6.spec
ci/concourse/scripts/greenplum-db-7.spec
ci/concourse/scripts/test-functionality-rpm.bash
ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb

Remove Photon3 platform for gpdb6

---

ci/concourse/pipelines/gpdb-package-testing.yml

Update artifacts name after taint

---

ci/concourse/pipelines/gpdb-package-testing.yml

Fix gpdb6 client rocky9/oel9/rhel9 rpm test have correct platform

---

CONTRIBUTING.md

Changes CLA in CONTRIBUTING.md

---

Makefile
ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb7-opensource-release.yml

Update license-file to gpdb-osl for 6X and 7X OSS release pipeline

---

ci/concourse/pipelines/gpdb-opensource-release.yml
ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/pipelines/gpdb7-opensource-release.yml

Switch to gcr.io to fetch image to work around the error

Fix image fetch failure

---

ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Upgrade gp-tanzunet-client to 4.8.2

---

ci/concourse/pipelines/gpdb-package-testing.yml

Update bin_gpdb6_rocky9 resource

---

ci/concourse/pipelines/gpdb-package-testing.yml
ci/concourse/tasks/test-functionality-rpm.yml
ci/concourse/tests/gpdb7/server/conflicts/gpdb7-server-conflicts.rb
ci/concourse/tests/gpdb7/server/upgrade/controls/gpdb7-server-upgrade.rb
ci/concourse/vars/gpdb-package-testing.dev.yml
ci/concourse/vars/gpdb-package-testing.prod.yml

previous released 7.0.0-beta.0 has been marked admin's only, so need to upgrade 7.0.0

Update gpdb7 version

---

ci/concourse/pipelines/gpdb-package-testing.yml

Update add_component artifacts for gpdb6

---

ci/concourse/scripts/greenplum-db-6.spec

GPDB6: Use system provided Python 3.9 on EL9

---

ci/concourse/scripts/greenplum-db-7.spec

Fixes libgomp missing dependency issue for el8 gpdb7 package-testing

---

ci/concourse/vars/greenplum-database-release.dev.yml
ci/concourse/vars/greenplum-database-release.prod.yml

Upgrade gp-tanzunet-client to 4.8.3

---

ci/concourse/tests/gpdb6/server/install/controls/gpdb6-server-install.rb

[GPR-1639]
Authored-by: Anusha Shakarad <shakarada@vmware.com>

Unvendor python3.9 for el9 platform so no need of the test case

---

ci/concourse/pipelines/gpdb7-opensource-release.yml

GP7: add RHEL9 release for OSS pipeline
